<?php

namespace DoctrineProxies\__CG__\App\Models;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Models\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'casts' => [parent::class, 'casts', null],
        "\0".'*'."\0".'email' => [parent::class, 'email', null],
        "\0".'*'."\0".'email_verified_at' => [parent::class, 'email_verified_at', null],
        "\0".'*'."\0".'hidden' => [parent::class, 'hidden', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'name' => [parent::class, 'name', null],
        "\0".'*'."\0".'password' => [parent::class, 'password', null],
        "\0".'*'."\0".'rememberToken' => [parent::class, 'rememberToken', null],
        'casts' => [parent::class, 'casts', null],
        'email' => [parent::class, 'email', null],
        'email_verified_at' => [parent::class, 'email_verified_at', null],
        'hidden' => [parent::class, 'hidden', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'password' => [parent::class, 'password', null],
        'rememberToken' => [parent::class, 'rememberToken', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
